### ISSUE TITLE
Any chance for an armhf gemian release?

### ISSUE THREAD

**Issue by szopin** [gemian/cosmo-linux-kernel-4.4#1]
Not really sure where to file this, but just curious if maybe armhf release would be more stable? As any armhf specific bugs  would most likely be already fixed by jolla, as sailfish is still 32bit, so things like kwin crashes might just go away (just guessing and no idea if there are armhf drivers, or we're stuck with arm64)

**Comment by NotKit** [comment]
Sorry for the late reply. armhf is technically possible (wirh arm64 kernel, but that works for Sailfish), but I don't think it will bring many improvements and it requires building all Gemian-specific packages for two architectures.

**Comment by szopin** [comment]
sorry, out of curiosity how much is that? I was wondering if having a sid version of gemian would be worth it but no idea how much upkeep would be needed (afraid to just plug their repos in, sadly pulling just .debs doesn't work, latest FF for example wants to pull the whole house with glibc etc and force installing doesn't work)

**Comment by NotKit** [comment]
The amount of packages just to get something to boot is rather small, but for telephony, power management, etc with components ported from Mer and Ubuntu Touch it quickly grows into a long list. See this GitHub organization and http://gemian-buster.thinkglobally.org/jenkins/ for overview.

**Comment by szopin** [comment]
Awesome stuff thank You! Sorry to make this issue a general chat thingie but outside of IGG comments it's really hard to contact you guys, any chance we could partake in beta testing of telephony working as mentioned in previous igg update? Even if it's partial or buggy, maybe more eyes can help weed out the bugs?

**Comment by NotKit** [comment]
I'm not at Planet actually, so those are different communication channels. For me, it would be easiest to explain what to install if you joined Gemini PDA chat on Telegram (https://t.me/GeminiPDA) or Matrix.
