### ISSUE TITLE
[Request] USBC to HDMI Cosmo Support

### ISSUE THREAD

**Issue by zero77** [gemian/cosmo-linux-kernel-4.4#2]
Can you please add support for usb c to hdmi dual screen support for the cosmo communicator, at the moment it's not being detected at all, when you connect a usbc to hdmi cable.

**Comment by adamboardman** [comment]
The kernel fully supports this, the android vs gemian kernel changes are very small and not in this area. Its the [display driver](https://github.com/gemian/xf86-video-hwcomposer/tree/buster-hwc2) that needs to have support added.

General 'I don't know where this bug should be raised' bugs are best placed alongside the wiki: https://github.com/gemian/gemian/issues
